### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [jwchau/imdb-clone#1]
- [x] Contains correct datatypes 
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null 
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and back_ticked
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and back_ticked

**Comment by linakherchi** [comment]
Are taggerable_id and tag_id foreign keys ? If so, can you specifically state it in the details column? 
Why is taggerable_id bigint ?

Thank you !

**Comment by jwchau** [comment]
fixed taggerable id and tag_id to have foreign key in detail column.
changed taggerable_id datatype to be integer.

**Comment by linakherchi** [comment]
Hi John ! The checklist is for me to be able to track your progress. Please refrain from checking it. This will allow me what to review with you for our next meeting, and what you need to modify. Thank you !

**Comment by jwchau** [comment]
> Hi John ! The checklist is for me to be able to track your progress. Please refrain from checking it. This will allow me what to review with you for our next meeting, and what you need to modify. Thank you !

Sorry, just read this comment now. I will refrain from checking it in the future.
