### ISSUE TITLE
State Shape

### ISSUE THREAD

**Issue by linakherchi** [jwchau/imdb-clone#2]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by jwchau** [comment]
Updated sample state.

Please advise.

**Comment by linakherchi** [comment]
Good job, John ! 

Only modification is your sample state that needs to be correctly formatted using the triple back-ticks.

**Comment by jwchau** [comment]
Sorry, I'm don't understand. Is it a certain section that needs triple back-ticks?
